Repository cyfronet-fid/sat4envi, pull requests merged in 2020-01, with the labels that each got.

#306 Backend dependencies update - 2020.01
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
  s4e-backend/pom.xml
  s4e-backend/src/main/java/pl/cyfronet/s4e/Application.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/SecurityConfig.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/GroupController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/InstitutionController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/PlaceController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SavedViewController.java
  s4e-web/pom.xml
Labels: dependencies

#318 [#313] Report modal html/css
  s4e-web/src/app/modal/components/generic-modal/generic-modal.component.html
  s4e-web/src/app/modal/components/generic-modal/generic-modal.component.scss
  s4e-web/src/app/modal/components/modal-outlet/modal-outlet.component.scss
  s4e-web/src/app/views/map-view/map-view.component.scss
  s4e-web/src/app/views/map-view/report-modal/report-modal.component.html
  s4e-web/src/app/views/map-view/report-modal/report-modal.component.scss
  s4e-web/src/app/views/map-view/report-modal/report-modal.component.ts
  s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.scss
  s4e-web/src/scss/_common.scss
  s4e-web/src/scss/_modal.scss
  s4e-web/src/scss/_variables.scss
Labels: front-end

#285 [#252] Sync params with url
  s4e-web/package-lock.json
  s4e-web/package.json
  s4e-web/src/app/app.module.ts
  s4e-web/src/app/utils/initializer/config.service.ts
  s4e-web/src/app/utils/rxjs/observable.ts
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.scss
  s4e-web/src/app/views/map-view/map-view.component.spec.ts
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map.module.ts
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/state/map/map.model.ts
  s4e-web/src/app/views/map-view/state/map/map.query.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.service.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.service.ts
  s4e-web/src/app/views/map-view/state/map/map.store.spec.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.factory.spec.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts
  s4e-web/src/app/views/map-view/state/product/product.service.ts
  s4e-web/src/app/views/map-view/state/product/product.store.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.ts
  s4e-web/src/app/views/map-view/timeline/timeline.component.html
  s4e-web/src/app/views/map-view/timeline/timeline.component.ts
  s4e-web/src/app/views/settings/groups/group-form/group-form.component.ts
  s4e-web/src/app/views/settings/groups/group-list/group-list.component.ts
  s4e-web/src/app/views/settings/people/person-form/person-form.component.ts
  s4e-web/src/app/views/settings/people/person-list/person-list.component.ts
  s4e-web/src/app/views/settings/state/institution.service.ts
  s4e-web/src/main.ts
Labels: front-end

#334 [#333] Add sanity e2e tests
  .github/workflows/maven.yml
  README.md
  s4e-web/cypress/integration/sanity.spec.ts
  s4e-web/cypress/plugins/cy-ts-preprocessor.js
  s4e-web/cypress/plugins/index.js
  s4e-web/package-lock.json
  s4e-web/package.json
Labels: infrastructure

#344 [#342] Add download link for original file in current scene
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.scss
  s4e-web/src/app/views/map-view/map-view.component.spec.ts
  s4e-web/src/app/views/map-view/map-view.component.ts
Labels: front-end
