Repository cyfronet-fid/sat4envi, pull requests merged in 2020-11, with the labels that each got.

#867 Fix search product URL id
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts
Labels: bug, front-end

#770 [#767] Remove layer name field from wms overlay response
  CHANGELOG.md
  s4e-backend/src/main/java/pl/cyfronet/s4e/bean/WMSOverlay.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/OverlayController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/request/OverlayRequest.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/OverlayService.java
  s4e-backend/src/main/resources/db/migration/V57__alter_overlay.sql
  s4e-backend/src/test/java/pl/cyfronet/s4e/OverlayHelper.java
  s4e-web/src/app/views/map-view/state/overlay/overlay.factory.spec.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/wms-url.utils.ts
Labels: back-end, front-end

#764 [#759] Image WMS validation
  s4e-web/cypress/integration/map/map-layers.spec.ts
  s4e-web/cypress/page-objects/map/map-layers.po.ts
  s4e-web/src/app/views/map-view/map/map.component.spec.ts
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/state/overlay/image-wms.utils.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.query.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.utils.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.html
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.scss
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.spec.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/wms-url.utils.ts
Labels: front-end

#866 [#799] Add live scene loading
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/state/product/product.service.spec.ts
  s4e-web/src/app/views/map-view/state/product/product.service.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.ts
  s4e-web/src/app/views/map-view/state/scene/scene.store.service.ts
  s4e-web/src/app/views/map-view/state/scene/timeline.service.spec.ts
  s4e-web/src/app/views/map-view/state/scene/timeline.service.ts
  s4e-web/src/app/views/map-view/timeline/timeline.component.html
  s4e-web/src/app/views/map-view/timeline/timeline.component.scss
  s4e-web/src/app/views/map-view/timeline/timeline.component.spec.ts
  s4e-web/src/app/views/map-view/timeline/timeline.component.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.spec.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/environments/environment.common.ts
Labels: front-end

#860 [#786] OL Loading indicator should only be affected by last OL request
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.utils.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.ts
  s4e-web/src/app/views/map-view/state/utils/layers-loader.util.ts
  s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.ts
Labels: bug, front-end

#857 E2E authorization tests update
  s4e-web/cypress.json
  s4e-web/cypress/fixtures/users/userToRegister.json
  s4e-web/cypress/integration/auth/auth-login.spec.ts
  s4e-web/cypress/integration/auth/auth-too-many-requests.spec.ts
  s4e-web/cypress/integration/auth/register.spec.ts
  s4e-web/cypress/integration/map/map-favorite-products.spec.ts
  s4e-web/cypress/integration/map/map-get-jwt-token.spec.ts
  s4e-web/cypress/integration/map/map-layers.spec.ts
  s4e-web/cypress/integration/map/map-locations-search.spec.ts
  s4e-web/cypress/integration/map/map-products.spec.ts
  s4e-web/cypress/integration/map/map-views.spec.ts
  s4e-web/cypress/integration/settings/settings-breadcrumbs.spec.ts
  s4e-web/cypress/integration/settings/settings-change-password.spec.ts
  s4e-web/cypress/integration/settings/settings-dashboard.spec.ts
  s4e-web/cypress/integration/settings/settings-institution-profile.spec.ts
  s4e-web/cypress/integration/settings/settings-institutions-list.spec.ts
  s4e-web/cypress/integration/settings/settings-invitations-list.spec.ts
  s4e-web/cypress/integration/settings/settings-user-profile.spec.ts
  s4e-web/cypress/page-objects/auth/login.po.ts
  s4e-web/cypress/page-objects/auth/register.po.ts
  s4e-web/cypress/page-objects/map/map-jwt-token-modal.po.ts
  s4e-web/cypress/page-objects/map/map.po.ts
  s4e-web/cypress/page-objects/settings/settings-side-nav.po.ts
Labels: automatic testing

#876 [Fix] User details in profile
  s4e-web/src/app/views/settings/profile/profile.component.html
  s4e-web/src/app/views/settings/profile/profile.component.ts
Labels: bug, front-end

#911 [#907] Add endpoint count for front-search and API
  s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/SearchController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryExt.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/SceneRepositoryImpl.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/PreparedStatementBuilder.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilder.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryBuilderImpl.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryDecorator.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java
Labels: back-end

#912 [Fix] Scroll page position to top on navigate in settings
  s4e-web/src/app/views/settings/settings.component.ts
Labels: front-end

#913 Load map and open modal on send view
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.service.ts
  s4e-web/src/app/views/map-view/zk/list-configs-modal/list-configs-modal.component.html
  s4e-web/src/app/views/map-view/zk/list-configs-modal/list-configs-modal.component.ts
Labels: front-end

#900 [#898] choose dashboard by number of institutions
  s4e-web/cypress/integration/settings/settings-breadcrumbs.spec.ts
  s4e-web/cypress/integration/settings/settings-change-password.spec.ts
  s4e-web/cypress/integration/settings/settings-dashboard.spec.ts
  s4e-web/cypress/integration/settings/settings-institution-profile.spec.ts
  s4e-web/cypress/integration/settings/settings-institutions-list.spec.ts
  s4e-web/cypress/integration/settings/settings-user-profile.spec.ts
  s4e-web/package-lock.json
  s4e-web/package.json
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.spec.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts
  s4e-web/src/app/views/settings/dashboard/dashboard.component.html
  s4e-web/src/app/views/settings/dashboard/dashboard.component.ts
  s4e-web/src/app/views/settings/dashboards.routes.ts
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html
  s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.spec.ts
  s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.ts
  s4e-web/src/app/views/settings/people/invitation-form/invitation-form.component.ts
  s4e-web/src/app/views/settings/people/person-list/person-list.component.html
  s4e-web/src/app/views/settings/people/person-list/person-list.component.ts
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts
  s4e-web/src/app/views/settings/profile/profile.component.ts
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.routes.ts
  s4e-web/src/app/views/settings/state/institution/institution.query.ts
  s4e-web/src/app/views/settings/state/institution/institution.service.ts
  s4e-web/src/scss/_rwd_phone.scss
  s4e-web/src/scss/_rwd_tablet.scss
  s4e-web/src/scss/_settings.scss
  s4e-web/src/scss/styles.scss
Labels: front-end

#965 [#964] Fix forget-me endpoint
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/AppUserService.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/controller/AppUserControllerTest.java
Labels: back-end

#954 Add ability to remove institutions
  s4e-web/src/app/state/session/session.model.ts
  s4e-web/src/app/state/session/session.query.ts
  s4e-web/src/app/views/settings/manage-authorities/manage-authorities.component.html
  s4e-web/src/app/views/settings/manage-authorities/manage-authorities.component.scss
  s4e-web/src/app/views/settings/manage-authorities/manage-authorities.component.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html
  s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.ts
  s4e-web/src/app/views/settings/people/person-list/person-list.component.html
  s4e-web/src/app/views/settings/people/state/person/person.model.ts
  s4e-web/src/app/views/settings/people/state/person/person.query.ts
  s4e-web/src/app/views/settings/people/state/person/person.service.ts
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.module.ts
  s4e-web/src/app/views/settings/settings.routes.ts
Labels: front-end

#962 [#880, #863] Show details for scene and allow artifact download
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.spec.ts
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.html
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.spec.ts
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.model.ts
  s4e-web/src/app/views/map-view/state/scene/scene.factory.spec.ts
  s4e-web/src/app/views/map-view/state/scene/scene.model.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts
  s4e-web/src/scss/_common.scss
Labels: front-end

#970 [#967] Remove unique name constraint from wms_overlay
  s4e-backend/src/main/resources/db/migration/V63__remove_name_unique_constraint_from_wms_overlay_table.sql
Labels: back-end
