Repository cyfronet-fid/sat4envi, pull requests merged in 2020-10, with the labels that each got.

#714 [#713] Copy JWT token to clipboard on map in user floating button
  CHANGELOG.md
  s4e-web/cypress/integration/map/map-get-jwt-token.spec.ts
  s4e-web/cypress/page-objects/map/map-jwt-token-modal.po.ts
  s4e-web/cypress/page-objects/map/map.po.ts
  s4e-web/src/app/state/form/form.model.ts
  s4e-web/src/app/state/session/session.service.ts
  s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.html
  s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.scss
  s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.spec.ts
  s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.component.ts
  s4e-web/src/app/views/map-view/jwt-token-modal/jwt-token-modal.model.ts
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map.module.ts
Labels: front-end

#756 [#722] Hide actions in settings by institution roles
  CHANGELOG.md
  s4e-web/cypress.json
  s4e-web/src/app/views/settings/dashboard/dashboard.component.html
  s4e-web/src/app/views/settings/dashboard/dashboard.component.spec.ts
  s4e-web/src/app/views/settings/dashboard/dashboard.component.ts
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.spec.ts
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts
  s4e-web/src/app/views/settings/manage-institutions/add-institution/add-institution.component.scss
  s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html
  s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.ts
  s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.spec.ts
  s4e-web/src/app/views/settings/manage-institutions/parent-institution-modal/parent-institution-modal.component.ts
  s4e-web/src/app/views/settings/profile/profile.component.html
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/state/institution/institution.query.ts
Labels: front-end

#720 [#717] Image WMS URL validation
  CHANGELOG.md
  restart-core-containers.sh
  s4e-web/cypress/integration/map/map-layers.spec.ts
  s4e-web/cypress/page-objects/login/login.po.ts
  s4e-web/cypress/page-objects/map/map-layers.po.ts
  s4e-web/cypress/page-objects/modal/confirm-modal.po.ts
  s4e-web/src/app/modal/components/confirm-modal/confirm-modal.component.html
  s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.html
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.spec.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/overlay-list-modal.component.ts
  s4e-web/src/app/views/map-view/view-manager/overlay-list-modal/wms-url.utils.ts
Labels: front-end

#758 [#751] UI Data Binding
  s4e-web/package-lock.json
  s4e-web/package.json
  s4e-web/src/app/app.configuration.spec.ts
  s4e-web/src/app/app.module.ts
  s4e-web/src/app/app.providers.ts
  s4e-web/src/app/modal/components/generic-modal/generic-modal.component.scss
  s4e-web/src/app/modal/components/modal-outlet/modal-outlet.component.scss
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.scss
  s4e-web/src/app/views/map-view/map-view.component.spec.ts
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map.module.ts
  s4e-web/src/app/views/map-view/map/map.component.scss
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.html
  s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.html
  s4e-web/src/app/views/map-view/sentinel-search/search-results/search-results.component.scss
  s4e-web/src/app/views/map-view/sentinel-search/sentinel-search.component.spec.ts
  s4e-web/src/app/views/map-view/state/common.model.ts
  s4e-web/src/app/views/map-view/state/location-search-results/locations-search-results.service.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.model.ts
  s4e-web/src/app/views/map-view/state/map/map.query.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.service.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.service.ts
  s4e-web/src/app/views/map-view/state/map/map.store.spec.ts
  s4e-web/src/app/views/map-view/state/map/map.store.ts
  s4e-web/src/app/views/map-view/state/product/product.model.ts
  s4e-web/src/app/views/map-view/state/product/product.query.spec.ts
  s4e-web/src/app/views/map-view/state/product/product.query.ts
  s4e-web/src/app/views/map-view/state/product/product.service.spec.ts
  s4e-web/src/app/views/map-view/state/product/product.service.ts
  s4e-web/src/app/views/map-view/state/product/product.store.spec.ts
  s4e-web/src/app/views/map-view/state/product/product.store.ts
  s4e-web/src/app/views/map-view/state/scene/scene.query.spec.ts
  s4e-web/src/app/views/map-view/state/scene/scene.service.spec.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.factory.spec.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.model.ts
  s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.query.spec.ts
  s4e-web/src/app/views/map-view/state/view-configuration/view-configuration.service.spec.ts
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.html
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.spec.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/map-view/zk/list-configs-modal/list-configs-modal.component.spec.ts
  s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.spec.ts
  s4e-web/src/scss/_common.scss
  s4e-web/src/scss/_map.scss
  s4e-web/src/scss/_modal.scss
  s4e-web/src/scss/_rwd_tablet.scss
  s4e-web/src/scss/_sidebar.scss
  s4e-web/src/scss/styles.scss
Labels: front-end

#766 [#765] [Fix] Show overlay loading indicator
  s4e-web/src/app/views/map-view/state/map/map.service.spec.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.model.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.query.spec.ts
Labels: bug, front-end

#730 [Fix] E2e optimization and longer timeout
  .github/workflows/maven.yml
  s4e-web/cypress.json
  s4e-web/cypress/integration/map/map-favorite-products.spec.ts
  s4e-web/cypress/integration/map/map-layers.spec.ts
  s4e-web/cypress/integration/map/map-locations-search.spec.ts
  s4e-web/cypress/integration/map/map-products.spec.ts
  s4e-web/cypress/integration/settings/settings-invitations-list.spec.ts
  s4e-web/cypress/page-objects/core.po.ts
  s4e-web/cypress/page-objects/login/login.po.ts
  s4e-web/cypress/page-objects/map/map-layers.po.ts
  s4e-web/cypress/page-objects/map/map-locations-search.po.ts
  s4e-web/cypress/page-objects/map/map-products.po.ts
  s4e-web/cypress/page-objects/map/map-views.po.ts
  s4e-web/cypress/page-objects/map/map.po.ts
  s4e-web/cypress/page-objects/modal/general-modal.po.ts
  s4e-web/cypress/page-objects/settings/settings-add-institution-form.po.ts
  s4e-web/cypress/page-objects/settings/settings-dashboard.po.ts
  s4e-web/cypress/page-objects/settings/settings-institution-list.po.ts
  s4e-web/cypress/page-objects/settings/settings-institution-people.po.ts
  s4e-web/cypress/page-objects/settings/settings-institution-profile.po.ts
  s4e-web/cypress/page-objects/settings/settings-institution-search.po.ts
  s4e-web/cypress/page-objects/settings/settings-parent-institution-modal.po.ts
  s4e-web/cypress/page-objects/settings/settings-side-nav.po.ts
  s4e-web/cypress/page-objects/settings/settings-user-profile.po.ts
  s4e-web/package-lock.json
  s4e-web/package.json
Labels: automatic testing, bug
