Repository cyfronet-fid/sat4envi, pull requests merged in 2020-04, with the labels that each got.

#415 [#403] Add favourite Products
  CHANGELOG.md
  s4e-backend/src/main/java/pl/cyfronet/s4e/bean/Product.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/ProductController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/controller/response/BasicProductResponse.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/ProductRepository.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/ProductService.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/util/SecurityHelper.java
  s4e-backend/src/main/resources/db/migration/V31__add_favourite_product_app_users_table.sql
  s4e-backend/src/test/java/pl/cyfronet/s4e/controller/ProductControllerTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/service/ProductServiceTest.java
Labels: back-end

#429 [#427] [Bugfix] places input should keep state
  CHANGELOG.md
  s4e-web/cypress/integration/product-navigation.spec.ts
  s4e-web/src/app/views/map-view/state/search-results/search-results.service.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
Labels: bug, front-end

#431 [#423] Notifications module
  CHANGELOG.md
  s4e-web/.gitignore
  s4e-web/angular.json
  s4e-web/package-lock.json
  s4e-web/package.json
  s4e-web/projects/notifications/ng-package.json
  s4e-web/projects/notifications/package.json
  s4e-web/projects/notifications/src/jest.setup.js
  s4e-web/projects/notifications/src/lib/components/dynamic-notification/dynamic-notification.component.html
  s4e-web/projects/notifications/src/lib/components/dynamic-notification/dynamic-notification.component.scss
  s4e-web/projects/notifications/src/lib/components/dynamic-notification/dynamic-notification.component.spec.ts
  s4e-web/projects/notifications/src/lib/components/dynamic-notification/dynamic-notification.component.ts
  s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.html
  s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.scss
  s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.spec.ts
  s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.ts
  s4e-web/projects/notifications/src/lib/components/notification-outlet/notification-outlet.component.html
  s4e-web/projects/notifications/src/lib/components/notification-outlet/notification-outlet.component.scss
  s4e-web/projects/notifications/src/lib/components/notification-outlet/notification-outlet.component.spec.ts
  s4e-web/projects/notifications/src/lib/components/notification-outlet/notification-outlet.component.ts
  s4e-web/projects/notifications/src/lib/components/notification.component.ts
  s4e-web/projects/notifications/src/lib/notifications.module.ts
  s4e-web/projects/notifications/src/lib/notifications.tokens.ts
  s4e-web/projects/notifications/src/lib/state/notification.model.ts
  s4e-web/projects/notifications/src/lib/state/notification.query.spec.ts
  s4e-web/projects/notifications/src/lib/state/notification.query.ts
  s4e-web/projects/notifications/src/lib/state/notification.service.spec.ts
  s4e-web/projects/notifications/src/lib/state/notification.service.ts
  s4e-web/projects/notifications/src/lib/state/notification.store.spec.ts
  s4e-web/projects/notifications/src/lib/state/notification.store.ts
  s4e-web/projects/notifications/src/lib/utils/notification-mapper.service.spec.ts
  s4e-web/projects/notifications/src/lib/utils/notification-mapper.service.ts
  s4e-web/projects/notifications/src/lib/utils/utils.spec.ts
  s4e-web/projects/notifications/src/lib/utils/utils.ts
  s4e-web/projects/notifications/src/public_api.ts
  s4e-web/projects/notifications/src/scss/_variables.scss
  s4e-web/projects/notifications/src/scss/notifications.scss
  s4e-web/projects/notifications/tsconfig.lib.json
  s4e-web/projects/notifications/tsconfig.spec.json
  s4e-web/projects/notifications/tslint.json
  s4e-web/src/app/app.module.ts
  s4e-web/src/app/components/root/root.component.html
  s4e-web/src/app/components/root/root.component.scss
  s4e-web/src/app/components/root/root.component.ts
  s4e-web/src/scss/styles.scss
  s4e-web/tsconfig.json
Labels: front-end

#436 [#435] Notifications for share configuration
  CHANGELOG.md
  s4e-web/package.json
  s4e-web/projects/notifications/src/lib/components/general-notification/general-notification.component.spec.ts
  s4e-web/src/app/views/map-view/zk/configuration/state/configuration.service.spec.ts
  s4e-web/src/app/views/map-view/zk/configuration/state/configuration.service.ts
  s4e-web/src/tsconfig.spec.json
Labels: front-end

#426 [#158] Password change front
  .gitignore
  CHANGELOG.md
  s4e-web/.gitignore
  s4e-web/cypress/integration/product-navigation.spec.ts
  s4e-web/cypress/integration/profile.spec.ts
  s4e-web/package.json
  s4e-web/src/app/state/form/form.model.ts
  s4e-web/src/app/state/profile/profile.model.ts
  s4e-web/src/app/state/profile/profile.service.ts
  s4e-web/src/app/views/login/login.component.html
  s4e-web/src/app/views/login/login.component.ts
  s4e-web/src/app/views/map-view/state/product/product.service.ts
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.html
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.spec.ts
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/settings/profile/profile.component.html
  s4e-web/src/app/views/settings/profile/profile.component.scss
  s4e-web/src/app/views/settings/profile/profile.component.spec.ts
  s4e-web/src/app/views/settings/profile/profile.component.ts
Labels: front-end
