Repository cyfronet-fid/sat4envi, pull requests merged in 2020-07, with the labels that each got.

#565 [#562][#558] fix dropdowns toggling, Institution edition, registration form, add child institution and cancel password change
  CHANGELOG.md
  s4e-web/src/app/components/form-error/form-error.component.html
  s4e-web/src/app/components/form-error/form-error.component.ts
  s4e-web/src/app/components/root/root.component.ts
  s4e-web/src/app/state/session/session.service.ts
  s4e-web/src/app/utils.ts
  s4e-web/src/app/views/login/login.component.ts
  s4e-web/src/app/views/login/login.module.ts
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/state/location-search-results/locations-search-results.service.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts
  s4e-web/src/app/views/settings/breadcrumb/breadcrumb.service.ts
  s4e-web/src/app/views/settings/dashboard/dashboard.component.ts
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.html
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-list/institution-list.component.html
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.html
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.spec.ts
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts
  s4e-web/src/app/views/settings/profile/profile.module.ts
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.routes.ts
  s4e-web/src/app/views/settings/state/institution/institution.service.ts
  s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.query.spec.ts
  s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.query.ts
Labels: front-end

#530 67 api search
  CHANGELOG.md
  pom.xml
  s4e-backend/pom.xml
  s4e-backend/src/main/java/pl/cyfronet/s4e/api/ODataController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/api/OSearchController.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchApiParams.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/api/SearchConverter.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/config/QueryConfig.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/config/SecurityConfig.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryEnding.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryGeometry.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/data/repository/query/QueryText.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/search/SearchQueryParams.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneFileStorageService.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/SceneStorage.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/service/SearchService.java
  s4e-backend/src/main/java/pl/cyfronet/s4e/util/GeometryUtil.java
  s4e-backend/src/main/resources/db/migration/V38__add_gist_index_footprint_scene_table.sql
  s4e-backend/src/test/java/pl/cyfronet/s4e/SceneTestHelper.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/api/ODataControllerTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/api/OSearchControllerTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/api/SearchConverterTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/controller/SearchControllerTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/service/SceneFileStorageServiceTest.java
  s4e-backend/src/test/java/pl/cyfronet/s4e/service/SearchServiceTest.java
Labels: back-end

#575 [#573] Create children tree list in settings institution-profile
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.html
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.component.ts
  s4e-web/src/app/views/settings/intitution-profile/institution-profile.module.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.spec.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
  s4e-web/src/app/views/settings/state/institution/institution.service.spec.ts
  s4e-web/src/app/views/settings/state/institution/institution.service.ts
  s4e-web/src/app/views/settings/state/institutions-search/institutions-search-results.query.ts
Labels: front-end

#569 [#566] resize `Warstwy` segment in `/map` sidebar, [Fix] Update UI messages
  CHANGELOG.md
  s4e-web/package-lock.json
  s4e-web/package.json
  s4e-web/src/app/components/search/search.component.html
  s4e-web/src/app/components/search/search.component.spec.ts
  s4e-web/src/app/views/login/login.component.html
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map.module.ts
  s4e-web/src/app/views/map-view/view-manager/layer-picker/layer-picker.component.scss
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/map-view/zk/configuration/share-configuration-modal/share-configuration-modal.component.ts
  s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.html
  s4e-web/src/app/views/map-view/zk/report-modal/report-modal.component.ts
  s4e-web/src/app/views/map-view/zk/save-config-modal/save-config-modal.component.html
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
Labels: bug, front-end

#572 [#571] [Fix] Hide groups and it's functionalities
  CHANGELOG.md
  s4e-web/src/app/views/settings/dashboard/dashboard.component.html
  s4e-web/src/app/views/settings/people/person-form/person-form.component.html
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.routes.ts
Labels: front-end

#587 [#583] Cookie based auth front end
  s4e-web/.angular-ssl/server.crt
  s4e-web/.angular-ssl/server.key
  s4e-web/angular.json
  s4e-web/cypress.json
  s4e-web/src/app/app.module.ts
  s4e-web/src/app/modal/utils/modal/modal.component.ts
  s4e-web/src/app/state/common-state.module.ts
  s4e-web/src/app/state/form/form.model.ts
  s4e-web/src/app/state/profile/profile.model.ts
  s4e-web/src/app/state/profile/profile.query.spec.ts
  s4e-web/src/app/state/profile/profile.query.ts
  s4e-web/src/app/state/profile/profile.service.spec.ts
  s4e-web/src/app/state/profile/profile.service.ts
  s4e-web/src/app/state/profile/profile.store.spec.ts
  s4e-web/src/app/state/profile/profile.store.ts
  s4e-web/src/app/state/session/session.factory.spec.ts
  s4e-web/src/app/state/session/session.model.ts
  s4e-web/src/app/state/session/session.query.spec.ts
  s4e-web/src/app/state/session/session.query.ts
  s4e-web/src/app/state/session/session.service.ts
  s4e-web/src/app/state/session/session.store.ts
  s4e-web/src/app/utils/auth-interceptor/auth.interceptor.spec.ts
  s4e-web/src/app/utils/auth-interceptor/auth.interceptor.ts
  s4e-web/src/app/utils/initializer/config.service.spec.ts
  s4e-web/src/app/utils/initializer/config.service.ts
  s4e-web/src/app/views/login/login.component.ts
  s4e-web/src/app/views/map-view/map-view.component.spec.ts
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map/map.component.spec.ts
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/settings/breadcrumb/breadcrumb.module.ts
  s4e-web/src/app/views/settings/breadcrumb/breadcrumb.service.ts
  s4e-web/src/app/views/settings/dashboards.routes.ts
  s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.spec.ts
  s4e-web/src/app/views/settings/guards/is-manager/is-manager.guard.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-form/files.utils.ts
  s4e-web/src/app/views/settings/manage-institutions/institution-form/institution-form.component.ts
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.spec.ts
  s4e-web/src/app/views/settings/profile/change-password/change-password.component.ts
  s4e-web/src/app/views/settings/profile/profile.component.spec.ts
  s4e-web/src/app/views/settings/settings.breadcrumbs.ts
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.module.ts
  s4e-web/src/app/views/settings/settings.routes.ts
Labels: front-end

#597 [#595] Timestamp limits in scenes GET request
  s4e-web/src/app/views/map-view/map/map.component.ts
  s4e-web/src/app/views/map-view/state/overlay/overlay.service.ts
Labels: front-end

#594 [#592] Create events directive
  CHANGELOG.md
  s4e-web/src/app/components/root/root.component.ts
  s4e-web/src/app/components/search/search.component.html
  s4e-web/src/app/components/search/search.component.spec.ts
  s4e-web/src/app/components/search/search.module.ts
  s4e-web/src/app/utils.ts
  s4e-web/src/app/utils/dropdown/events.directive.spec.ts
  s4e-web/src/app/utils/dropdown/events.directive.ts
  s4e-web/src/app/utils/dropdown/events.module.ts
  s4e-web/src/app/views/map-view/map-view.component.html
  s4e-web/src/app/views/map-view/map-view.component.ts
  s4e-web/src/app/views/map-view/map.module.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.spec.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.module.ts
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.module.ts
Labels: front-end

#600 [#556] Add keys handling for search
  CHANGELOG.md
  s4e-web/src/app/components/search/search.component.html
  s4e-web/src/app/components/search/search.component.scss
  s4e-web/src/app/components/search/search.component.spec.ts
  s4e-web/src/app/components/search/search.component.ts
  s4e-web/src/app/components/search/search.module.ts
  s4e-web/src/app/utils/search/activated-queue.utils.ts
  s4e-web/src/app/utils/search/events.directive.spec.ts
  s4e-web/src/app/utils/search/events.directive.ts
  s4e-web/src/app/utils/search/events.module.ts
  s4e-web/src/app/views/map-view/map.module.ts
  s4e-web/src/app/views/map-view/sentinel-search/search-result-modal/search-result-modal.component.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.spec.ts
  s4e-web/src/app/views/map-view/state/sentinel-search/sentinel-search.service.ts
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.html
  s4e-web/src/app/views/map-view/view-manager/view-manager.component.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.html
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.component.ts
  s4e-web/src/app/views/settings/admin-dashboard/admin-dashboard.module.ts
  s4e-web/src/app/views/settings/settings.component.html
  s4e-web/src/app/views/settings/settings.component.ts
  s4e-web/src/app/views/settings/settings.module.ts
Labels: front-end
